#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : psycopg2
Version  : 2.6.1
Release  : 9
URL      : https://pypi.python.org/packages/source/p/psycopg2/psycopg2-2.6.1.tar.gz
Source0  : https://pypi.python.org/packages/source/p/psycopg2/psycopg2-2.6.1.tar.gz
Summary  : psycopg2 - Python-PostgreSQL Database Adapter
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0 ZPL-2.0
Requires: psycopg2-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : postgresql-dev
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
psycopg2 - Python-PostgreSQL Database Adapter
=============================================

%package python
Summary: python components for the psycopg2 package.
Group: Default

%description python
python components for the psycopg2 package.


%prep
%setup -q -n psycopg2-2.6.1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
